% -------------------------------------------------------------------
%  Generated by MATLAB on 14-Mar-2019 21:07:29
%  MATLAB version: 9.5.0.1049112 (R2018b) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('point_transformation_inbuild.mat');

ans = saveVarsMat.ans; % <256x256 uint8> too many elements

i = saveVarsMat.i; % <256x256 uint8> too many elements

i1 = false;

id = saveVarsMat.id; % <256x256 double> too many elements

id1 = saveVarsMat.id1; % <256x256 double> too many elements

id2 = saveVarsMat.id2; % <256x256 uint8> too many elements

y = saveVarsMat.y; % <256x256 uint8> too many elements

clear saveVarsMat;
