% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Mar-2019 21:21:47
%  MATLAB version: 9.5.0.1049112 (R2018b) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('resizingimages_inbuilt.mat');

B = saveVarsMat.B; % <159x191 uint8> too many elements

Dblue = saveVarsMat.Dblue; % <135x198 uint8> too many elements

Dgray = saveVarsMat.Dgray; % <135x198 uint8> too many elements

Dgreen = saveVarsMat.Dgreen; % <135x198 uint8> too many elements

Dred = saveVarsMat.Dred; % <135x198 uint8> too many elements

a = saveVarsMat.a; % <256x256 uint8> too many elements

ans = struct;
ans.Filename = ['C:\Program Files\MATLAB\R2018b\toolbox\images\imdata\h' ...
                'otcoffee.tif'];
ans.FileModDate = '27-Mar-2015 15:22:58';
ans.FileSize = 307396;
ans.Format = 'tif';
ans.FormatVersion = [];
ans.Width = 320;
ans.Height = 240;
ans.BitDepth = 32;
ans.ColorType = 'grayscale';
ans.FormatSignature = [73 73 42 0];
ans.ByteOrder = 'little-endian';
ans.NewSubFileType = 0;
ans.BitsPerSample = 32;
ans.Compression = 'Uncompressed';
ans.PhotometricInterpretation = 'BlackIsZero';
ans.StripOffsets = 8;
ans.SamplesPerPixel = 1;
ans.RowsPerStrip = 4.294967295E+9;
ans.StripByteCounts = 307200;
ans.XResolution = [];
ans.YResolution = [];
ans.ResolutionUnit = 'Inch';
ans.Colormap = [];
ans.PlanarConfiguration = 'Chunky';
ans.TileWidth = [];
ans.TileLength = [];
ans.TileOffsets = [];
ans.TileByteCounts = [];
ans.Orientation = 1;
ans.FillOrder = 1;
ans.GrayResponseUnit = 0.01;
ans.MaxSampleValue = 4.294967295E+9;
ans.MinSampleValue = 0;
ans.Thresholding = 1;
ans.Offset = 307208;
ans.ImageDescription = 'Copyright The MathWorks, Inc.';
ans.Software = 'MATLAB';
ans.SampleFormat = 'IEEE floating point';

b = saveVarsMat.b; % <537x358 uint8> too many elements

bmap = [];

c = saveVarsMat.c; % <128x128 double> too many elements

c0 = saveVarsMat.c0; % <256x256 double> too many elements

c1 = saveVarsMat.c1; % <256x256 double> too many elements

c2 = saveVarsMat.c2; % <256x256 double> too many elements

c3 = saveVarsMat.c3; % <256x256 double> too many elements

c4 = saveVarsMat.c4; % <256x256 double> too many elements

c5 = saveVarsMat.c5; % <256x256 double> too many elements

c6 = saveVarsMat.c6; % <256x256 double> too many elements

c7 = saveVarsMat.c7; % <256x256 double> too many elements

cc = saveVarsMat.cc; % <256x256 double> too many elements

cd = saveVarsMat.cd; % <256x256 double> too many elements

cd1 = saveVarsMat.cd1; % <256x256 double> too many elements

columns = 256;

d = saveVarsMat.d; % <135x198x3 uint8> too many elements

i = 129;

img1 = saveVarsMat.img1; % <512x1024 uint8> too many elements

img2 = saveVarsMat.img2; % <512x1024 double> too many elements

j = 1;

m = saveVarsMat.m; % <206x345 uint8> too many elements

rows = 256;

x = saveVarsMat.x; % <256x256 uint8> too many elements

y = saveVarsMat.y; % <128x128 uint8> too many elements

z = saveVarsMat.z; % <512x512 uint8> too many elements

zmap = [];

clear saveVarsMat;
